### ISSUE TITLE
GraphQL API `packets` 추가

### ISSUE THREAD

**Issue by msk** [aicers/giganto#114]
다음과 같은 API를 추가합니다.

```graphql
packets(filter: RawEventFilterInput!, after: String, before: String, first: Int, last: Int): [String!]!
```

`RawEventFilterInput`은 #87 을 참고하세요.

패킷을 읽어오는 것은 별도 이슈에서 다루고, 이 이슈에서는 빈 array를 돌려주도록 합니다.

**Comment by syncpark** [comment]
@msk @kimhanbeom 

Packet Request API 이슈:

기본적으로 Web UI에서 탐지한 이벤트를 판정할 때 패킷을 사용합니다. 이 경우 한 번에 하나의 PCAP 파일을 요청합니다.
요청메시지를 다음처럼 수정했으면 합니다.
    ```graphql
    packets(filter: RawEventFilterInput!): String!
    ```
    Paging을 위한 옵션을 삭제했고, 리턴 값이 Array가 아니라 단일 문자열입니다. 다만 리턴값의 경우 PCAP 파일이 존재하지 않을 수 있으니 Option으로 바꿔야 하지 않을까요?

**Comment by kimhanbeom** [comment]
RawEventFilterInput 은 현재 범위 조회를 위해 사용하는 구조체입니다. 
```rust
RawEventFilterInput {
  time: TimeRange
  source: String,
  origAddr: IpRange
  respAddr: IpRange
  origPort: PortRange
  respPort: PortRange
}

TimeRange {
  start: DateTime!
  end: DateTime!
}

IpRange {
  start: String!
  end: String!
}

PortRange {
  start: Int!
  end: Int!
}
```

특정 패킷을 가져오기 위한 필터 구조체는 아래와 같이 구성하면 될까요?
```rust
PcapFilterInput {
  source: String!
  time: DateTime!
  origAddr: String!
  respAddr: String!
  origPort: Int!
  respPort: Int!
}
```

**Comment by msk** [comment]
> 기본적으로 Web UI에서 탐지한 이벤트를 판정할 때 패킷을 사용합니다. 이 경우 한 번에 하나의 PCAP 파일을 요청합니다. 요청메시지를 다음처럼 수정했으면 합니다.

@syncpark pcap 파일이 꽤 클텐데, 파일 단위로 요청을 하는 이유는 뭔가요?

**Comment by syncpark** [comment]
@msk @kimhanbeom 여기서 요청하는 PCAP 파일은 탐지한 이벤트에 해당하는 세션의 패킷입니다. 대개의 경우 매우 작은 크기일 겁니다. 매우 큰 HTTP 기반의 파일 다운로드나 SMTP 첨부 파일을 포함하는 패킷같은 경우를 제외하면요.

그리고 판정 화면에서는 보통 탐지 이벤트 단위로 판정을 하거든요. 한 건 기준으로요. 여기에 해당하는 패킷 덤프(세션 기준)가 한 건 뿐이라서 한 건 단위로 요청합니다.

**Comment by syncpark** [comment]
@msk @kimhanbeom 그리고 패킷의 내용을 요청하는 경우는 판정화면에서 PCAP 파일 링크를 클릭했을 때 입니다. 이때 해당 PCAP 파일을 PC로 다운로드해서 Wireshark 같은 프로그램으로 분석한다...가 현재까지의 설계 내용입니다.

물론 특정 고객 - KT - 의 경우처럼 화면에 기본적인 패킷 덤프 내용(마치 Wireshark 처럼)을 보여주기를 원한다면, 판정화면에 들어갈 때마다 PCAP 파일을 요청하게 됩니다.

**Comment by msk** [comment]
> 그리고 패킷의 내용을 요청하는 경우는 판정화면에서 PCAP 파일 링크를 클릭했을 때 입니다. 이때 해당 PCAP 파일을 PC로 다운로드해서 Wireshark 같은 프로그램으로 분석한다...가 현재까지의 설계 내용입니다.
> 
> 물론 특정 고객 - KT - 의 경우처럼 화면에 기본적인 패킷 덤프 내용(마치 Wireshark 처럼)을 보여주기를 원한다면, 판정화면에 들어갈 때마다 PCAP 파일을 요청하게 됩니다.

그럼 pcap 파일 헤더는 굳이 giganto에서 매번 붙여서 보내줄 필요가 없지 않나요? 그냥 패킷만 보내주는게 나을 것 같은데요.

**Comment by syncpark** [comment]
> 그럼 pcap 파일 헤더는 굳이 giganto에서 매번 붙여서 보내줄 필요가 없지 않나요? 그냥 패킷만 보내주는게 나을 것 같은데요.

처음 데이터 저장 플랫폼 기능을 설계할 때는 PCAP 파일을 Piglet에서 모두 가져와서 모아놓는 것으로 검토했습니다. 그럼 한 군데 모든 PCAP 파일이 모여있으니 거기서 검색을 하려면 별도의 메타정보가 있어야 했는데, 그때 그 헤더에 포함된 정보를 이용할 예정이었습니다.

이제 Piglet에 모두 저장해두기로 했으니 조금 다를 수 있습니다.

Original PCAP에서 필요한 세션에 해당하는 PCAP을 추출해서 실시간으로 전송하고 별도 저장하지 않는다면, 검색을 위한 별도 헤더는 필요 없을테지만, 이후 재사용을 위해서는 저장할 때 그 파일을 검색할 때 사용할 별도 정보-인덱스 혹은 필터링 역할-가 필요합니다.

**Comment by msk** [comment]
> Original PCAP에서 필요한 세션에 해당하는 PCAP을 추출해서 실시간으로 전송하고 별도 저장하지 않는다면, 검색을 위한 헤더는 필요 없을테지만, 이후 재사용을 위해서는 PCAP 파일을 검색할 때 사용할 별도 정보-인덱스 혹은 필터링 역할-가 필요합니다.

일단은 패킷만 전송하는 것으로 하고, 인덱스 추가 등은 나중에 성능 문제가 생기면 고려하는게 어떨까요?

**Comment by syncpark** [comment]
> 일단은 패킷만 전송하는 것으로 하고, 인덱스 추가 등은 나중에 성능 문제가 생기면 고려하는게 어떨까요?

그럼 PCAP을 REview에게 전송하면, 그 이후에는 계속 REview에서만 그 파일을 관리하면 되겠네요?

**Comment by msk** [comment]
> > 일단은 패킷만 전송하는 것으로 하고, 인덱스 추가 등은 나중에 성능 문제가 생기면 고려하는게 어떨까요?
> 
> 그럼 PCAP을 REview에게 전송하면, 그 이후에는 계속 REview에서만 그 파일을 관리하면 되겠네요?

관리가 필요한가요? 매번 다시 piglet에서 검색하면 안 될까요?

**Comment by syncpark** [comment]
> > 그럼 PCAP을 REview에게 전송하면, 그 이후에는 계속 REview에서만 그 파일을 관리하면 되겠네요?
> 
> 관리가 필요한가요? 매번 다시 piglet에서 검색하면 안 될까요?

그럼 요청메시지 세션 정보에 따라 트래픽 PCAP에서 그 세션에 해당하는 패킷을 추출해서 저장해두고 나중에 같은 요청이 오면 그 파일을 검색해서 전송해준다는 의미인가요? 그렇다면 굳이 REview에서 관리할 필요 없습니다. 이 경우 Piglet에서 이들 추출 패킷들에 대해서는 데이터 손실 방지 기능(Data loss prevention aicers/piglet#295) 관련 기능 요구사항에 반영할 필요가 있겠네요.

이게 아니라면 아래 사항을 고민해야 됩니다.
탐지한 이벤트에 해당하는 패킷 추출 요청 시점(탐지 시점)과 그 추출 PCAP을 Web UI에서 사용하는 시점(화면에서 PCAP 링크를 클릭해서 다운로드하는 시점)이 다른데, 대개의 경우 탐지 시점에 패킷을 추출해서 저장해두지 않으면, 사용 시점에는 패킷을 추출할 원본 트래픽 PCAP 파일이 존재하지 않을 가능성이 매우 높습니다.

KT 프로젝트의 경우 10Gbps 회선 2개를 통해서 트래픽이 꽉 찬 상태로 유입되니 시간당 저장되는 용량이 4TB 이상입니다. 시스템 스펙(수집장비는 대개 10TB 이하)으로 봤을 때 트래픽 최대 저장 시간이 2시간이 안될 것으로 예상합니다. 리오 프로젝트는 이보다 훨씬 여유가 있어서 최소 5배 이상의 시간적 여유가 있지만, 그래봐야 몇 일 정도 저장할 수 있습니다.

이때문에 미리 탐지한 이벤트에 해당하는 패킷만 별도 추출해서 저장해둬야 합니다.

**Comment by msk** [comment]
(1) 저장해 둘 패킷 선정과 (2) 패킷 사용 두 가지 기능이 있는데, @syncpark 은 (1)번을, 저는 (2)번을 얘기하고 있어서 혼란이 생긴 것 같습니다.

요구사항을 제가 좀 더 명확히 이해하기 위해 질문 드리겠습니다.

1. (1)은 누가 요청을 보내나요?
2. (1)은 GraphQL이어야하나요?

**Comment by syncpark** [comment]
> * (1)은 누가 요청을 보내나요?

탐지하는 모듈, 즉, Hog, REconverge가 요청(혹은 REview)을 보냅니다. Hog의 경우 DNS Covert Channel이 탐지될 경우, 그리고 만일 이 Category에 해당하는 공격이 발생했을 때 패킷을 저장하라는 옵션이 설정되어 있다면, 탐지하지마자 요청을 Piglet으로 보내야 합니다.

다른 방식도 가능합니다. 일단 REview에 탐지 결과가 모두 수집되니, REview는 탐지 결과를 받자마자 Category 별로 PCAP 추출 옵션을 확인하고, 추출 요청 메시지를 보낼 수 있습니다.

REconverge는 클러스터링이 끝난 후 라벨링 결과 혹은 위협 클러스터에 들어온 이벤트들에 대한 PCAP 추출 요청을 직접 Piglet으로 보내거나 REview가 수집해서 Piglet으로 요청을 보낼 수 있습니다.

> * (1)은 GraphQL이어야하나요?

추출 요청 시점에서는 GraphQL을 사용하는게 더 번거롭습니다. 탐지 이벤트의 시간, 5-tuple, 수집 장비 정보만 보내는게 좋습니다.

하지만 사용시점에서는 Web UI로부터 요청이 발생하니 시작 메시지가 GraphQL입니다. 그리고 외부 협력업체 연동(PCAP은 아니지만 비슷한 EML 파일의 요청)은 GraphQL을 사용하는게 더 효율적인거 같습니다.

**Comment by msk** [comment]
그럼 현 단계에서는 (pcap 파일이 아닌) 패킷만 돌려주는 것으로 API를 만들어 놓고, pcap 파일을 어떻게 할 것인지는 나중에 설계 방향을 보고 결정하는 것이 좋겠습니다. 데이터 장기 보존은 giganto가 담당하고 있으니, 선정된 패킷은 giganto에 저장하도록 하는 것도 나쁘지 않아보이거든요.

**Comment by syncpark** [comment]
> 그럼 현 단계에서는 (pcap 파일이 아닌) 패킷만 돌려주는 것으로 API를 만들어 놓고, pcap 파일을 어떻게 할 것인지는 나중에 설계 방향을 보고 결정하는 것이 좋겠습니다. 데이터 장기 보존은 giganto가 담당하고 있으니, 선정된 패킷은 giganto에 저장하도록 하는 것도 나쁘지 않아보이거든요.

예. 그렇게 하시지요.
