### ISSUE TITLE
rocksdb flush 호출 이슈 

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/giganto#141]
현재 giganto는 데이터 수신 확인 응답을 보내는 기능을 구현되어 있습니다.(https://github.com/aicers/giganto/issues/30)
기능 구현 부분중  rocksdb에 저장을 확실히 하기 위해 `flush`를 사용하고 있는데, `flush`를 호출 할 때 마다 파일이 생성되고, 해당 파일이 전부 open 상태로 되어 있어, 데이터 수신 시작 후 일정 시간 경과하면 `too many open file error` 가 발생하고 그 후부터  quic 통신 및 db 저장이 되지 않게 됩니다.  그렇기 때문에 아래의 2가지 이슈에 대한 수정이 필요로 합니다.
 - flush 호출시 매번 파일 생성
 - 생성된 파일이 전부 open 상태

**Comment by msk** [comment]
제가 RocksDB API를 잘못 알고 있어서 생긴 문제입니다. WAL buffer를 디스크에 저장하는 것이 목적이므로 `flush`가 아니라 [`flush_wal`](https://docs.rs/rocksdb/latest/rocksdb/struct.DBCommon.html#method.flush_wal)을 호출해야 합니다.
