### ISSUE TITLE
Crusher로부터 전달받은 시계열 데이터를 저장하기

### ISSUE THREAD

**Issue by sehkone** [aicers/giganto#175]
시계열 데이터를 저장하고 성공적으로 저장했는지 여부를 crusher에게 알려줍니다. Giganto가 전송하는 내용에 대한 사항은 [해당 이슈](https://github.com/aicers/crusher/issues/12)를 참고하세요.

**Comment by sehkone** [comment]
ACK 여부로 저장 여부를 확인할 수 있으면 충분합니다.

**Comment by kimhanbeom** [comment]
crusher 와의 time series 관련 내용 정리하여 올립니다.

1. crusher에서 giganto의 time series 채널 연결
 - time_series 타입 전송 : 0x05 (u32,litten endian)
 

2. crusher에서 생성된 시계열 데이터 전송
 - start : i64 (little endian)          //주기 시작
 - data size:  u32 (little endian) //시계열 데이터 사이즈 
 - data : bincode serialize          //시계열 데이터 (data는 구조체로 필드는 다음과 같이 정의)
    -  model_id : String 
    - data : Vec<f64>


3. giganto에서 데이터를 저장
 - key : model_id + start
 - value: data
