### ISSUE TITLE
REconverge로부터 프로토콜 데이터 요청에 따른 데이터 전송

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#180]
REconverge는 Giganto가 수집해서 저장하고 있는 Conn, Http, Dns, Smtp 등의 데이터를 요청할 수 있습니다.

- [ ] Source를 지정하지 않고, 프로토콜 데이터를 요청할 수 있습니다. Source(수집 장비)를 지정하지 않으면 모든 Source로부터 수집된 프로토콜 데이터를 전달해야 합니다.
- [ ] REproduce가 전송한 Log DB의 내용뿐아니라 Conn, Http, Dns 등의 DB에 저장된 데이터도 전송(Publish)해야 합니다.
- [ ] REconverge에게 전송하는 데이터는 CSV, Log(비정형 데이터), Email, Packet 중의 한가지 형태여야 합니다.  
        REconverge는 structure 형태의 데이터를 사용하지 않습니다.
        Conn, Http, Dns 등의 데이터를 REconverge에게 전송할 때는 CSV 형식의 데이터로 전송해야 합니다.
- [ ] 프로토콜 데이터를 전송할 때는 앞부분에 "시간", "Source(수집장비 이름)" 필드값을 추가해서 전송해야 합니다.

Highest priority job:
* REconverge can get `HTTP` events from Giganto that the events are produced at a `source` machine by Piglet

**Comment by kimhanbeom** [comment]
giganto쪽에서 1차적으로 구현해야되는 내용을 정리하였습니다.

1. 멀티 source / 전체 source에 대한 부분은 다음 issue에서 처리합니다. 현 issue에서는 특정 source에 대해서만 처리 하도록 합니다.
2. `REconverge`가  요청하는 타입은 현재 2가지 입니다. 이중 `Log` 타입으로 오는 것에 대해서 log/protocol을 전부 처리 하도록 합니다.
    ```rust
    enum MessageCode {
        Log = 0,
        PeriodicTimeSeries = 1,
    } 
    ```
3. `REconverge`로부터 `Log` 타입을 수신한 경우, `Message` 의 `kind` 필드를 검토합니다. `kind` 값이 `conn`/`dns`/`rdp`/`http`인 경우 프로토콜 데이터 요청으로 판단합니다. 그외의 값이면 기존에 작성 되어 있는 log 처리를 수행합니다. 
    ```rust
    struct Message {
        source: String,
        kind: String,
        start: i64,
        end: i64,
        count: usize,
    }
   ```
5. `kind` 가  `conn`/`dns`/`rdp`/`http`인 경우,  해당 프로토콜과 에 맞는 db에서 값을 읽어서 csv형식으로 생성하여 데이터를 구성합니다.
6.  csv 데이터를 구성할때 매번 데이터의 맨앞에 timestamp와 source의 값을 추가합니다.
