### ISSUE TITLE
제공하는 query에 total count 추가

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/giganto#189]
현재 giganto가 제공하는 모든 query에  total count 필드를 추가힙니다. 
해당 필드 값은 요청 query에 있는 필터링 조건까지 만족하는 총 결과값의 갯수를 의미합니다.

**Comment by msk** [comment]
필터링 조건까지 만족하는 결과값 갯수를 구하려면 매번 상당히 많은 이벤트에 대해 읽기, deserialization, 필터 조건 비교를 거쳐야 해서 로드가 상당히 큽니다.

@sehkone 필터링 조건을 만족하는 이벤트 갯수를 구하는 건 안 하기로 하지 않았나요?

**Comment by kimhanbeom** [comment]
해당 필드 추가에 로드가 커서 추가하지 않기로 하였습니다. 해당 이슈는 닫겠습니다.
