### ISSUE TITLE
time series 관련 publish  버그 수정

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/giganto#191]
현재 time series 관련 publish request/response 에 대한 버그가 있습니다.
https://github.com/aicers/giganto/issues/175 의 수정을 통해 time series는  ingestion에서 다음과 같이 저장됩니다.
- key : sampling policy id + timestamp   
- value: data

1.publish에서 request 수신시 아래와 같은 메세지를 수신합니다.
```rust
struct Message {
    source: String,
    kind: String,
    start: i64,
    end: i64,
    count: usize,
}
```
그리고 이를 통해 database를 조회시 key를 source + kind(sampling policy id)+ timestamp 로  사용하고 있기 때문에 time series를 정상적으로 조회 할 수 없습니다.

2.time series의  database 저장 값은 ingestion으로 들어오는 struct 전부가 아닌 data 만 저장합니다. 
(sampling policy id는 key에 포함되어 있기 때문에 저장 할 의미가 없으므로 제외)
```rust
pub struct PeriodicTimeSeries {
    pub id: String,
    pub data: Vec<f64>,
}
```
그렇기 때문에 publish에서 request 수신시 database에서 읽어온  time series 데이터를 deserialize 할 경우 저장된 값과 struct의 형태가 틀려서 무조건 프로그램이 종료 되기 때문에 이에 대한 처리가 필요합니다.

**Comment by BLYKIM** [comment]
이전에 구두로 나눴던 것 처럼 현재 구현된 기능이
bincode serialize로 저장된 각각의 struct들을 활용하기 때문에
db의 value에 `PeriodicTimeSeries`의 id, data를 저장하기로 하면 별도의 추가코드 없이 많은 부분이 해결 될 것 같습니다.
현재 publish의 timeseries를 보내는 코드도 `timeseries.data`를 보내고있고
현재 pr에 올라간 graphql부분도 마찬가지로 id 저장될 것을 염두에 두고 수정되어있구요.
