### ISSUE TITLE
zeek파일(conn/http/rdp/smtp)을 통한 database 추가

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/giganto#193]
giganto가 시작했을때 설정한 경로에 있는 zeek파일을 읽어서 각각의 프로토콜(conn/http/rdp/smtp)에 해당되는 database에 insert 합니다.

**Comment by msk** [comment]
특정 애플리케이션의 로그 파일을 읽어들이는 건 giganto가 할 일이 아닌 것 같은데요. giganto의 데이터베이스에 넣는 목적으로는 ingestion 프로토콜이 있으니, (1) 임시로 필요한 기능이라면 별도 프로그램으로 구현하고 (2) 앞으로도 계속 필요한 기능이라면 reproduce에 포함시키는 것이 맞지 않을까요?

**Comment by kimhanbeom** [comment]
@msk 
네 해당 기능은 지속적으로 사용 필요한 부분이라서 reproduce로 이동시키겠습니다.
해당 이슈는 여기서 close하겠습니다.
