### ISSUE TITLE
통계 생성, 저장, 관리

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#219]
### 통계 생성, 저장
* Giganto는 Piglet이 처리하는 데이터량에 대한 통계를 수집해서 저장해야 합니다.
* Giganto는 Giganto가 수집하는 이벤트에 대한 통계를 생성해서 저장해야 합니다.

### 통계 DB
* 통계 데이터를 저장할 DB 구성
* 통계의 종류
  * Piglet이 처리한 트래픽 총계
    * Piglet이 일정 시간 간격으로 트래픽 통계를 생성해서 전달하는 통계 데이터
  * Giganto가 수집하는 프로토콜별 이벤트 건수 및 크기
    * Source 별, 프로토콜(혹은 로그 종류) 별 이벤트 건수와 크기
    * 모든 Source의 이벤트 건수와 크기의 합계
    * 일정 시간 간격으로 저장
* 통계에 대한 검색 기능

**Comment by kimhanbeom** [comment]
해당 이슈의 giganto 수집 통계 부분은 부분적으로 구현된 [statistics branch](https://github.com/aicers/giganto/tree/statistics) 를 참조하여 구현하면 됩니다.

**Comment by kimhanbeom** [comment]
별개의 branch([statistics branch](https://github.com/aicers/giganto/tree/david-statistics))로 관리하여 필요시 사용할 예정이므로 이슈는 close 하겠습니다.
