### ISSUE TITLE
탐지이벤트에 대한 PCAP 추출 요청의 처리 및 추출한 PCAP 파일의 관리

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#247]
이번 이슈는 aicers/piglet#319 에 대한 갱신된 내용을 포함하고 있습니다. 이번 이슈가 완료되면 링크된 이슈도 함께 Close해도 됩니다.

탐지이벤트에 대한 PCAP 추출 요청의 처리 및 추출한 PCAP 파일의 관리:
- [x] Hog, REconverge에서 생성한 탐지이벤트를 REview에게 전달할 때 source(추출 장비 이름), protocol 필드 추가
- [x] REview에서 수신하는 탐지 이벤트에 source, protocol 필드 추가
  - RocksDB, GraphQL API에도 source 필드 추가. Protocol 필드 확인 및 추가
- [x] Hog, REconverge로부터 탐지이벤트에 대한 PCAP 추출 요청을 받아서 Piglet에게 전달
  - [x] Hog에서 Giganto로 요청메시지 전달
  - [x] REconverge에서 Giganto로 요청메시지 전달
  - [x] Giganto에서 Piglet으로 메시지 전달.
    - 탐지 이벤트 요청은 중복될 수 있습니다. 즉, Hog가 탐지한 이벤트를 REconverge가 탐지할 수도 있고, REconverge의 모델 다수에서 동시에 탐지할 수도 있습니다.
  - PCAP 추출 요청할 때 필요한 필드 8개: 시간, source(추출 장비 이름), 5-tuple, 세션 유지 시간(Duration)
  - 모든 이벤트 형식에 필드 추가: L4 protocol(tcp/udp/...)
- [x] Piglet이 추출한 PCAP을 패킷 단위의 이벤트로 받아서 RocksDB에 저장
  - Piglet이 Giganto에게 전달하는 메시지 구조: 시간(탐지 이벤트를 구분할 키값) + PCAP 파일을 패킷 단위로 분리해서 전달
  - RocksDB에 저장할 메시지 구조: Key = PCAP 추출 요청메시지의 시간 + 수집 장비 이름 + 패킷의 시간, Value(패킷)
- [x] GraphQL API로 PCAP 파일에 대한 요청을 받으면 RocksDB에서 찾아서 전달
  - 요청메시지 구조: Key: 시간 + 수집 장비이름
  - 응답메시지 데이터: PCAP에 속한 패킷들을 순서대로 전달

**Comment by BLYKIM** [comment]
예전 `packets` 관련 이슈인 #114 와 연관지어 변경할 수 있을까요 아니면 별개의 이슈인가요?

**Comment by msk** [comment]
RocksDB에는 pcap 파일 단위로 관리하는 것보다 패킷 단위로 관리하는 것이 낫지 않나요? 패킷 단위로 저장되어 있어야 특정 조건을 만족하는 패킷만 검색한다든지 하는 것이 용이할 것 같은데요.

**Comment by msk** [comment]
> PCAP 파일을 요청하는 UI에서 언제나 PCAP 파일 단위로 요청합니다. PCAP안에서 특정 패킷을 추출하는 것은 아직까지 고객 요청항목에 없습니다. 대부분 국내에서 판매되는 보안장비들을 보면 PCAP 단위로 사용합니다.

PCAP 파일로 필요한 시점에만 PCAP을 만들어주면 되지 않을까요? GraphQL에서 JSON을 요청한다고 데이터베이스에 JSON으로 저장하지는 않는 것처럼요.

패킷 단위로 저장하게 되면 다른 raw event 다루는 부분과 공유할 수 있는 코드도 많아지고, 유연성, 확장성 측면에서도 유리하지 않을까요? hog나 reconverge에서 요청한 것 외에도 아예 특정 프로토콜에 한해 최근 패킷을 모두 유지한다든지 할 때에도 같은 데이터베이스를 써도 되고, 저장되어 있는 패킷을 대상으로 다양한 통계를 낸다거나 하는 일도 가능해집니다.

**Comment by syncpark** [comment]
만약 패킷 단위로 분석하는 모델이나 기능이 Hog나 REconverge에 추가될 예정이라면, 당연히 RocksDB에 패킷 단위로 저장하는게 맞습니다만, 아직 그런 계획은 못들어봤습니다. 혹시 관련 계획이 있으신가요?

**Comment by msk** [comment]
> 만약 패킷 단위로 분석하는 모델이나 기능이 Hog나 REconverge에 추가될 예정이라면, 당연히 RocksDB에 패킷 단위로 저장하는게 맞습니다만, 아직 그런 계획은 못들어봤습니다. 혹시 관련 계획이 있으신가요?

계획은 없습니다만 코딩 부담이 늘어나는게 아니라면 유연성 있게 만들어 놓은 것이 좋겠지요.

PCAP 파일 단위로 저장할 때 장점은 어떤 것이 있나요?

**Comment by syncpark** [comment]
저는 PCAP 단위로만 사용한다면 굳이 패킷 단위로 나눠서 부담을 더할 필요는 없다고 생각했습니다.

그럼 패킷 단위로 저장하고, 전송하는 것으로 이슈를 수정하겠습니다.

**Comment by kimhanbeom** [comment]
@msk @syncpark @MW-Kim @BLYKIM 
해당 이슈는 상세 항목 구현 완료 및 piglet-giganto-reconverge/hog 간의 테스트까지 완료되어 close하겠습니다.
