### ISSUE TITLE
동일한 source의 ingest 접속 시 문제

### ISSUE THREAD

**Issue by BLYKIM** [aicers/giganto#268]
```rust
let source = certificate_info(&connection)?;

packet_sources
        .write()
        .await
        .insert(source.clone(), connection.clone());
```

동일 source에서 다른 장비가 접속 할 시 packet_sources의 value를 덮어씌웁니다. (Ex: reproduce)

**Comment by BLYKIM** [comment]
현재 구조상 `collect` 장비에 Piglet, REproduce만 사용하므로
REproduce의 경우 packet_sources에 insert하지 않는 것으로 수정하였고 (#269),
이후 전체적인 Handshake의 구조 수정이 요구됩니다.

**Comment by msk** [comment]
"동일 source에서 다른 장비가 접속"하는 경우는 어떻게 발생하나요? source마다 다 다른 인증서를 갖고 있는 것 아닌가요?

**Comment by BLYKIM** [comment]
@msk @syncpark 
다시 보니 "동일 장비"가 오해의 소지가 있을 수 있다고 생각합니다.
현재 인증서를 "collect", "analysis", "manage"와 같이 각 프로그램이 들어간 장비의 이름을 source로 쓰고있어서
"collect" 장비에 들어간 Piglet과 REproduce가 source가 동일한 상황입니다.

**Comment by msk** [comment]
그럼 giganto에서는 같은 인증서로 복수의 접속이 발생하는 걸 막고, 클라이언트는 전부 다른 인증서를 쓰도록 하는게 맞지 않나요? 인증서를 애초에 클라이언트 "인증"용으로 발급하는 건데, 서로 다른 클라이언트가 인증서를 공유하면 그것 자체가 문제인 것 같은데요.

**Comment by syncpark** [comment]
Giganto는 자신에게 이벤트를 전송하는 클라이언트의 인증서에서 장비이름을 추출하고, 그 값을 이벤트의 키값으로 사용합니다. 
이번 건은 REproduce가 전송하는 이벤트의 키값(수집 장비 이름)이 필요해서 같은 인증서를 사용했다가 발견한 문제입니다. 다른 이름을 갖는 인증서를 사용하면 수집 장비 이름이 바뀌기때문에 사용할 수 없는 상황이었습니다. 게다가 Piglet이 탐지 이벤트에 대한 PCAP을 추출해야하기 때문에 동시에 실행중이었습니다.

지금 인증서를 사용할 때 서버의 인증서의 Hostname을 Hosts 파일에 등록해두어야 인증이 정상적으로 동작하다보니 Host 단위로 인증서를 발급하고 있었습니다.

이후 작업 예정:
* REview에서처럼 Handshake할 때 클라이언트 정보(Agent ID, App name, Host ID, Version) 등을 보내는 방법으로 수정.
* Giganto는 수집 장비의 이름을 Handshake하면서 받은 Hostname을 수집해서 사용하도록 수정.
* 수정 대상: Piglet, REproduce, Crusher, Hog, REconverge. 

수정할 프로그램이 많아서 우선 긴급패치해서 현장 적용하고, 수정되는대로 다시 패치할 예정입니다.

**Comment by msk** [comment]
REview도 클라이언트에서 받는 agent ID를 없애고 인증서의 정보를 쓰는 쪽으로 바꾸려고 생각하고 있었는데요.

인증서에 hostname 외에 다른 정보를 더 넣을 수 있지 않나요? agent ID를 거기에 넣으면 같은 host에서 여러 agent가 동작하는 경우도 처리 가능할 것 같습니다.

**Comment by msk** [comment]
> 인증서에 hostname 외에 다른 정보를 더 넣을 수 있지 않나요? agent ID를 거기에 넣으면 같은 host에서 여러 agent가 동작하는 경우도 처리 가능할 것 같습니다.

확인해보니 가능합니다. 아래는 테스트용 인증서 내용인데요,

```
❯ openssl x509 -in cert.pem --text -noout
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 42 (0x2a)
        Signature Algorithm: ecdsa-with-SHA256
        Issuer: CN = rcgen self signed cert
        Validity
            Not Before: Jan  1 00:00:00 1975 GMT
            Not After : Jan  1 00:00:00 4096 GMT
        Subject: CN = rcgen self signed cert
        Subject Public Key Info:
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (256 bit)
                pub:
                    04:ee:49:cd:f9:3b:e8:2f:57:cc:5b:2c:bf:29:a6:
                    aa:4e:fd:ce:1c:88:c8:c6:5e:4b:fe:94:ad:97:ef:
                    65:ec:44:ce:5d:eb:65:91:d6:d1:02:1a:46:63:7d:
                    0e:10:c3:b7:49:9b:cb:71:cc:a9:98:d8:81:cd:76:
                    d9:b6:37:7c:97
                ASN1 OID: prime256v1
                NIST CURVE: P-256
        X509v3 extensions:
            X509v3 Subject Alternative Name:
                DNS:localhost
    Signature Algorithm: ecdsa-with-SHA256
         30:45:02:20:02:39:a2:d1:12:43:a2:ed:58:7e:d9:b2:1e:5f:
         d8:28:d0:0e:ad:7f:9c:9c:07:b9:fa:0a:ac:7b:d9:25:f5:f9:
         02:21:00:c0:31:3b:c9:d5:2e:7c:46:38:b2:89:68:9d:17:2b:
         21:73:9c:66:94:83:5d:f0:3d:2f:f1:bf:76:95:ac:f3:4a
```

여기서 인증서로 인증시 hostname을 체크하는 부분은 `DNS:localhost`입니다. 클라이언트별로 다른 이름을 주는 건 `Subject: CN = ...`에 저장하면 됩니다. 예를 들어 sensor1.example.com에 piglet과 reproduce를 실행하려면 인증서를 두 개를 만들고, 둘 다 `X509v3 Subject Altanative Name`에는 `DNS:sensor1.example.com`을 주고, piglet용 인증서에는 `Subject: CN = sensor1`, reproduce용 인증서에는 `Subject: CN = sensor2`와 같이 줄 수 있습니다. `Subject: CN = `에 들어가는 값은 해당 장비(sensor1.example.com)상에서만 겹치지 않는 문자열이면 됩니다.

**Comment by syncpark** [comment]
Agent ID라면 말씀하신대로 인증서의 Issuer 필드에 넣어도 됩니다. 하지만 이번 문제는 Agent ID가 아니라 App name을 구분할 필요해서 입니다.

같은 장비에서 서로 다른 Issuer CN을 갖는 인증서를 사용해서 Giganto에 접속하더라도 어느 연결이 Piglet인지 아니면 REproduce인지 구분할 수 없습니다. 패킷 추출 요청은 오직 Piglet에게만 전송해야하기 때문입니다.

그렇다면 Issuer CN에 `agent_id, app name`을 함께 넣어야 할까요?
그리고 이런 방식으로 인증서를 사용한다면 고객이 직접 발행한 인증서는 사용하지 못하게 막거나 아니면 지정한 방식으로 발행하도록 운영지침을 만들어야겠네요.

**Comment by BLYKIM** [comment]
#402
