### ISSUE TITLE
디스크 사용량 제어 - Usage limit

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#281]
디스크 사용량 제어가 현재 데이터 보관일자만 설정하도록 되어있습니다.
디스크 사용량 한계를 정하고 초과할 경우 오래된 데이터부터 삭제하는 기능을 추가해주세요.

기본 사용 한계: 디스크 크기의 80%

**Comment by kimhanbeom** [comment]
간단하게 rocksdb에서 제공되는 delete 함수들을 통해 테스트를 해보니 지정된 범위의 데이터를 삭제해도 실제 sst/log 파일이 정리되지 않아 디스크 용량이 줄어 들지는 않았습니다. 특정 데이터가 삭제 되도 실제 파일이 정리되는것은 `rocksdb level compaction`을 수행할 경우 이기 때문에 https://github.com/aicers/giganto/issues/280 을 통해 설정할 compaction option을 똑같이 가져와서 데이터 삭제시 때마다 수동으로 compaction을 수행하도록 해야 될 것 같습니다.

**Comment by syncpark** [comment]
@kimhanbeom
데이터가 삭제되어도 실제 점유율이 줄어들지 않는 상황은 인지했습니다.

하지만 디스크 사용율이 더 늘어나지 않도록 삭제 작업은 필요합니다. 데이터를 삭제하면 Compaction하기 전까지 점유율이 떨어지지는 않겠지만, 기존 점유 부분에 데이터를 저장하기때문에 디스크 사용율이 늘어나지는 않겠지요.

다만 디스크 점유율이 변하지 않아 그 값을 기준으로 삭제할 수는 없으니 날짜 비율로 삭제하는 건 어떨까요?

예를 들어: 사용 한계가 80%이고, 삭제 목표가 60%일 때.
가장 오래된 이벤트와 오늘 날짜의 차이가 100일이라면, 20% 차이인 20일치의 데이터를 삭제하면 될 것 같습니다. 그리고 Compaction을 하면 되겠지요. 만일 Compaction을 하지 않는다면 다음 번 실행할 때는 남은 80일치의 20%가 또 삭제될테니 Compaction을 해야합니다.

Compaction이 성능에 얼마나 영향을 주는지를 알 필요가 있겠습니다. 별다른 영향이 없다면 그냥 1일분량의 이벤트를 삭제하고 바로 Compaction을 해도 되니까요.
