### ISSUE TITLE
Too many file opend에 따른  rocksdb append 실패시 운영 검토 

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/giganto#283]
### 문제
- 현재 giganto에서 `rocksdb level compaction` 에 대한 상세 설정을 하지 않아 대량의 데이터를 append할 경우 파일이 대량으로 생겨나면서 어느 순간 `too many file open` 에러가 발생합니다. 
- 해당 에러가 발생할 경우 ingestion의 `store.append()`가 실패하여 해당 task가 종료되고 기존에 연결된 channel은 close 됩니다.
- crusher 의 이슈(https://github.com/aicers/crusher/issues/43) 또한 time series의 ingestion channel close가 원인으로 보입니다.
- packet 추출 요청 또한 `too many file open` 에러 발생할 경우, 추출 packet 저장이 안되는 이슈가 발생 할 수 있습니다.

### 해결 방안
- 현재 상황에서 append 실패하는 경우는 `too many file open` 의 경우 뿐이므로 , 해당 이슈(aicers/giganto/issues/280)를 완료하기 전까지는 에러 메세지와 함께 giganto 운영을 정지하도록 수정하도록 합니다.

**Comment by syncpark** [comment]
현재 `ulimit -a` 명령으로 확인했을 Ubuntu 시스템의 `open files` 기본 값은 1024입니다. 이 값을 50000개로 올려서 Giganto를 재실행해도 같은 에러가 계속 발생합니다.

Rocks DB 파일이 1000개를 초과하는 시점까지 소요된 날짜를 계산해서 그보다 이전 데이터를 자동으로 삭제하도록 `retention` 설정값을 지정해서 운영해야합니다.

**Comment by msk** [comment]
> 현재 `ulimit -a` 명령으로 확인했을 Ubuntu 시스템의 `open files` 기본 값은 1024입니다. 이 값을 50000개로 올려서 Giganto를 재실행해도 같은 에러가 계속 발생합니다.

혹시 giganto를 systemd로 실행한 경우인가요? 그렇다면 시스템 기본값과 상관없이 .service 파일에서 직접 지정해주어야 하는데 그래서 시스템 기본값을 50000으로 올려도 계속 에러가 나는게 아닌가 해서요.

**Comment by syncpark** [comment]
@kimhanbeom 이 이슈는 해결된것 같은데 확인해보시고 Close해주세요.

**Comment by kimhanbeom** [comment]
현재 file size 튜닝과 Ubuntu 시스템에서의 옵션 후 해당 문제가 재발생 되지 않아 close 합니다.
