### ISSUE TITLE
수신 확인 메시지 전송

### ISSUE THREAD

**Issue by msk** [aicers/giganto#30]
커넥션, DNS 등의 정보를 수신할 때, 각 채널별로 어디까지 디스크드라이브에 저장되었는지를 전송합니다. 예를 들어 piglet이 다음 timestamp로 DNS 정보를 보냈다면,

100 a.b.c
122 d.x.c
211 d.c.a

211이 디스크에 저장된 것을 확인하고(RocksDB의 flush 기능 이용), DNS 정보를 수신한 양방향 채널을 사용해서 211을 piglet에 전송합니다. 전송 시점은 다음 두 조건 중 하나라도 충족할 때입니다.

1. 채널 개시 후 혹은 마지막 수신 확인 전송 후 128개의 정보 수신
2. 채널 개시 후 혹은 마지막 수신 확인 전송 후 1분 경과

**Comment by kimhanbeom** [comment]
@msk 
구현 관련해서 궁금한 부분이 있어 comment를 남깁니다.

1. 위의 예시에서 주신 211은 timestamp만을 의미하는게 맞는건가요?
2. 수신 확인 메세지 전송 타이밍이 아래의 3가지 조건으로 보면 되는 건가요?
 1) 채널 개시 후 저장된 마지막 데이터를 전송(해당 채널에 대한 데이터가 있는 경우만)
 2) 특정 채널로 데이터 수신시 128번쨰 데이터를 수신한 경우 전송(128개 전송 단위 체크)
 3) 특정 채널로 마지막 데이터를 수신한 경우 전송

**Comment by msk** [comment]
> 1. 위의 예시에서 주신 211은 timestamp만을 의미하는게 맞는건가요?

맞습니다.

> 2. 수신 확인 메세지 전송 타이밍이 아래의 3가지 조건으로 보면 되는 건가요?
> 
> * 채널 개시 후 저장된 마지막 데이터를 전송(해당 채널에 대한 데이터가 있는 경우만)

채널 개시 직후에는 보낼 필요가 없습니다.

> * 특정 채널로 데이터 수신시 128번쨰 데이터를 수신한 경우 전송(128개 전송 단위 체크)
> * 특정 채널로 마지막 데이터를 수신 후 수신한 시간을 기준으로 1분 체크하여 1분이 경과한 경우 전송

이건 1. 둘 중에 하나라도 충족되면 전송하고, 2. 그 전송 시점부터 다시 128번째 데이터나 1분 경과 조건이 만족하면 또 전송하고, 2를 계속 반복합니다.
