### ISSUE TITLE
Giganto 인스턴스가 담당하지 않는 소스에 대한 GraphQL 요청 처리

### ISSUE THREAD

**Issue by msk** [aicers/giganto#326]
* 선행 이슈: #325

## 이슈 요약

Giganto 인스턴스가 GraphQL API를 통해 특정 소스에 대한 요청을 받았을 때, 해당 소스가 자신이 담당하는 소스가 아니라면 그 소스를 담당하는 인스턴스로 동일한 GraphQL 쿼리를 전달하여 데이터를 가져오도록 합니다.

## 기능 상세

1. Giganto 인스턴스가 GraphQL API 요청을 받고 해당 요청이 자신이 담당하는 소스인지 확인합니다.
2. 요청한 소스가 자신이 담당하는 소스라면 정상적으로 처리하고 응답을 반환합니다.
3. 요청한 소스가 자신이 담당하는 소스가 아니라면, 메모리에 저장된 피어-소스 매핑 정보를 사용하여 해당 소스를 담당하는 인스턴스를 찾습니다.
4. 찾은 인스턴스로 동일한 GraphQL 쿼리를 전달하고 결과를 가져옵니다.
5. 가져온 결과를 클라이언트에게 반환합니다.

## 예상 결과

* Giganto 인스턴스는 담당하는 소스에 대한 요청을 정상적으로 처리하고 응답할 수 있어야 합니다.
* Giganto 인스턴스는 담당하지 않는 소스에 대한 요청을 해당 소스를 담당하는 인스턴스로 전달하고, 결과를 가져와 반환할 수 있어야 합니다.

**Comment by sophie-cluml** [comment]
안녕하세요. 적어주신 기능 상세 2번 (`2. 요청한 소스가 자신이 담당하는 소스라면 정상적으로 처리하고 응답을 반환합니다.
`) 와 관련해 잘 이해했는지 확인 부탁드리고자 합니다.

<질문> 클러스터 내의 giganto는 항상 다른 모든 giganto peer들에게 GraphQL 쿼리를 전달하고 결과를 응답을 받아서 이를 전부 collect & sort해서 궁극적으로 graphql response를 반환해야하는 상황이 머리 속에 그려지고 있어서, 혹시 어떤 상황에서 giganto 가 다른 giganto peer들에게 쿼리를 전달하지 않고 스스로 곧바로 graphql response를 응답하는 시나리오가 발생하는지 궁금합니다. 

생각해본 사례를 예시로 들으면 다음과 같습니다. giganto cluster와 piglet이 다음과 같이 구성된다고 할 때,
```
giganto 1번서버 -- piglet 1,2,3번 /  giganto 2번서버 -- piglet 4,5,6번 / giganto 3번서버 -- piglet 7,8,9,10번
```
```
// piglet 1~10번의 toml 설정
protocols = [
  "conn", "dns", "ftp", { protocol = "http", port = [1080, 8888] }, "https", "kerberos",
  "ldap", "mqtt", "nfs", "rdp", "smb", "smtp"
]
```
이 상황에서 giganto 1번 서버로 graphQL API인 conn_raw_events가 인입되면, giganto 1번서버는 자신의 db.conn_store도 검색해야하지만, giganto 2,3번 서버의 db.conn_store 정보도 조합해야할 것 같아요.

혹시 piglet이 배타적으로 toml protocol 설정을 운영하게 될까요?

**Comment by syncpark** [comment]
상세 2번과 sophie가 예를 든 내용의 차이는 하나의 Piglet이 여러 Giganto에게 이벤트를 전송하느냐 아니냐의 차이로 보입니다.

Giganto가 GraphQL API Request로 특정 Source에 대한 요청을 받았을 때 요청한 Source가 자신의 DB에만 저장되어있다면 굳이 다른 Giganto에게 요청을 전달할 필요가 없을테고요. 만일 같은 Piglet의 데이터가 여러 Giganto에 나눠 저장되어있다면 당연히 다른 Giganto에게도 Query를 전달해야겠지요.

결론은 어느 Giganto에 어떤 Source의 데이터가 저장되어있는지 정보를 확인해서 Query 전달 여부를 결정하면 될것같습니다.

그리고 Piglet은 스위치로부터 미러링 받는 경우 그 스위치의 리소스 상당 부분을 사용합니다. 그래서 트래픽 미러링을 프로토콜 단위로 분리해서 별도의 Piglet으로 수집/분석하는 경우는 아직까지는 없었고, 앞으로도 잘 없을 것 같습니다.

**Comment by sophie-cluml** [comment]
@syncpark 확인 감사합니다.
유저가 graphQL API를 호출할 때 항상 source 정보 (piglet이든, reproduce는 CN에 적힌 노드 정보) 를 명시하도록 강제하는 룰 (RawEventFilter) 을 가져가는 배경이 있어서 말씀해주신 내용이 성립하는 것으로 이해되네요. 슬랙 드린 것은 무시해주시면 되겠습니다.

**Comment by syncpark** [comment]
@BLYKIM @kimhanbeom 이 두 사람이 더 잘 알겠네요. 두 분 답변 해주세요.

**Comment by BLYKIM** [comment]
@sophie-cluml 
- ExportFilter는 source_id가 source입니다.
- TimeSeries와 OpLog는 작업 제외해주시면 됩니다.
