### ISSUE TITLE
Giganto 인스턴스가 담당하지 않는 소스에 대한 publish 프로토콜 처리 (publish 중 message방식) 

### ISSUE THREAD

**Issue by msk** [aicers/giganto#327]
선행 이슈: #325 

## 이슈 요약

Giganto 인스턴스가 publish 프로토콜을 통해 특정 소스들에 대한 요청을 받았을 때, 그 중에 자신이 담당하는 소스가 아니 소스가 포함되어 있으면 그 소스를 담당하는 인스턴스로부터 데이터를 받아 자신의 데이터와 합친 후 반환하도록 합니다.

## 기능 상세

1. Giganto 인스턴스가 publish 프로토콜 요청을 받고 해당 요청이 자신이 담당하는 소스인지 확인합니다.
2. 요청한 소스가 모두 자신이 담당하는 소스라면 정상적으로 처리하고 응답을 반환합니다.
3. 요청한 소스 중에 자신이 담당하는 소스가 아닌 소스가 있으면, 메모리에 저장된 피어-소스 매핑 정보를 사용하여 해당 소스를 담당하는 인스턴스를 찾습니다.
4. 찾은 인스턴스에 publish 프로토콜로 요청을 전달하고 결과를 가져옵니다.
5. 가져온 결과를 자신의 데이터와 합친 후 반환합니다.

## 예상 결과

* Giganto 인스턴스는 담당하는 소스에 대한 publish 프로토콜 요청을 정상적으로 처리하고 응답할 수 있어야 합니다.
* Giganto 인스턴스는 담당하지 않는 소스에 대한 publish 프로토콜 요청을 해당 소스를 담당하는 인스턴스로 전달하고, 결과를 가져와 반환할 수 있어야 합니다.

**Comment by sophie-cluml** [comment]
@syncpark 안녕하세요. publish 에 있는 2가지 방식의 통신 (stream / message) 전부에 대해서 처리가 필요한가요?

**Comment by syncpark** [comment]
@sophie-cluml @kimhanbeom @BLYKIM 
Message 방식에 대한 클러스터 기능 지원은 Request를 받았을 때 다수의 Giganto에게 전송하고, 그 Response를 잘 정리해서 리턴하면 끝나는 1회성 동작 방식이었지요.

일단 Stream 방식에 대해 클러스터 기능 지원은 반드시 필요합니다.
다만 Stream 방식의 경우 클러스터 기능의 동작은 Message 방식과는 조금 다릅니다.

예상하는 TODO:
1. 소스가 지정된 Stream request를 받았을 때 해당하는 소스의 데이터를 가진 Giganto에게 Connection을 넘겨줘야(hand over)합니다. 이 경우 Hog, Crusher도 수정해야 겠네요.
    1.1 `처음 연결할 때` Hog, Crusher는 Giganto에 대한 `Connection`이 다른 Giganto로 넘어갈 수 있어야(`Hand over`) 합니다.
    1.2 `데이터가 전송되는 중간시점에` 요청했던 소스의 데이터가 다른 Giganto로 옮겨서 전송되기 시작할 경우 `Connection hand over`가 필요합니다.
2. 소스가 지정되지 않은, 즉, 모든 소스의 데이터를 요청한 경우 다른 모든 Giganto로부터 해당 프로토콜(Kind)의 이벤트를 받아서 시간 순서에 맞게 정렬해서 Hog, Crusher에게 전송해야 합니다.
    * 다만 이 경우는 고려해야할 점이 몇가지 더 있습니다. Hog의 경우 Giganto에게 Stream 데이터를 요청할 때 소스를 지정하거나 Giganto IP를 특정하는 이유는 너무 많은 이벤트로 인한 과부하를 걱정했기 때문입니다. 처음 Hog를 실행할 때부터 어떤 프로토콜, 어떤 소스의 데이터만 받아서 처리하도록 하자...라는 의도가 반영된 겁니다. 그런 의미에서 `1.1의 Connection hand over과 1.2`는 수용가능한 기능이지만, `2.`는 과부하를 유발할 수 있습니다. 정리하자면 `2.`에 해당하는 상황은 Giganto 클러스터 기능으로 해결하기 보다는 Hog에게 다수의 Giganto와의 Multiple connection을 구현하는 방식이 더 적합할 것 같습니다.

이렇게 적어놓고 보니 시간이 많이 걸릴것 같네요.

**Comment by syncpark** [comment]
@MW-Kim 내용 보고 검토해주세요.

**Comment by sophie-cluml** [comment]
네 저도 2번 케이스(소스 미지정케이스)의 존재 및 그 데이터 규모 핸들링 관점에서 이슈가 있다고 보고 stream 은 cluster가 아닌 다른 방식으로 문제를 해결해야한다고 생각하고 있습니다. 그리고 2번 케이스를 위해 hog가 multiple giganto connection을 할 수 있도록 구현한다면 1번케이스를 handover 구현하지 않고도 multiple connection 방식으로 간단히 핸들링될 수 있어보입니다. (hog가 모든 giganto에게 source-speicific stream요청을 보내면, 결국 source 를 가지고 있는 giganto만 stream 데이터를 전송해줄 것이고, 중간에 source가 연결된 giganto가 giganto1번에서 2번으로 변경되면, 자동으로 giganto2번이 hog에게 스트리밍을 해주는 방식으로 작동하기 때문)

**Comment by syncpark** [comment]
Giganto에 Connection이 조금 늘어나겠지만 이슈는 모두 해결할 수 있겠네요.
