### ISSUE TITLE
Giganto gets list of event Ids from clusters or outliers that matches search filter

### ISSUE THREAD

**Issue by marioEinsis** [aicers/giganto#331]
Aice-web send a vector of event Ids with a search filter as arguments and returns a list of event Ids that matches filter condition. Does not discriminate if outliers or clusters so only API.

**Comment by sehkone** [comment]
Giganto receives a list of event IDs in the format of` Vec<String, Vec<String>>`. The first `String` represents the cluster ID, and the last `String` represents the list of event IDs associated with that cluster. When Giganto returns the result, it should follow the same format.
