### ISSUE TITLE
FTP 수신, 저장 기능 추가

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#339]
FTP protocol event를 수신하고, 저장하기 위한 기능 추가
* 참조: Piglet branch issue-474-ftp

**Comment by kimhanbeom** [comment]
선행: https://github.com/aicers/giganto-client/issues/12, https://github.com/aicers/giganto-client/issues/11
giganto-client의 신규 프로토콜(ftp)을 사용하기 위해 신규 release 버전이 필요하므로 해당 내용이 전부 적용된 뒤 구현하도록 합니다.
