### ISSUE TITLE
데이터 수신

### ISSUE THREAD

**Issue by msk** [aicers/giganto#4]
선행 이슈: #1

양방향 채널로 들어오는 데이터를 다음과 같이 디코딩합니다.

* 처음 4바이트: record type (little-endian)
* 이후에는 (timestamp, record)의 반복
    * timestamp: 64-bit 정수, nanoseconds since January 1, 1970 UTC
    * record: 32-bit length (little-endian) + body
 
body는 추후 record type에 따라 decoding을 하겠지만, 이 이슈에서는 단순히 32-bit length만큼을 수신해서 버리는 것으로 합니다.

각 record를 수신할 때마다 record type, timestamp를 터미널에 출력합니다.

**Comment by kimhanbeom** [comment]
구현 중 궁금한점 있어 comment를 남깁니다.
데이터 송수신시 record type 과 record부분을 little endian으로 처리하는 이유가 궁금합니다.

**Comment by msk** [comment]
> 데이터 송수신시 record type 과 record부분을 little endian으로 처리하는 이유가 궁금합니다.

네트워크 프로토콜은 보통 big endian을 쓰지만 여기서 굳이 little endian으로 하는 건 bincode 때문에 그렇습니다. bincode 자체가 숫자를 little endian으로 인코딩하기 때문에, body는 little endian, 나머지는 big endian 이런 식으로 가면 오히려 헷갈릴 우려가 있어서요. 그냥 모든 경우에 대해서 little endian이라고 하는게 일관성 측면에서나, 프로그래밍 실수를 줄이는 측면에서나 나을 것 같아 그렇게 정했습니다.
