### ISSUE TITLE
네트워크 트래픽 필터 상세정보 추가

### ISSUE THREAD

**Issue by MW-Kim** [aicers/giganto#411]
## 이슈 요약
현재 저장된 raw log를 검색 할때 NetworkFilter 사용 합니다.

K사의 프로젝트를 진행할때 로그 상세 검색 이라는 기능이 있는데, 이때 조건값이 Http 프로토콜인 경우 method, host, uri, userAgent...등등 프로토을 조건 값으로 줄 수 있어야 합니다. 따라서, 기존의 NetworkFilter에 추가 조건이 필요 합니다.

## 기능 상세
목표: Conn을 포함하여 모든 프로토콜 이벤트들이 대상. 각 프로토콜 이벤트의 모든 필드에 대한 검색이 가능

구현 방법(예상):
방안 1. 프로토콜 별 상세 검색에 필요한 properties 들로 구성된 구조체를 생성해서 NetworkFilter에 구조체를 추가하는 방식
방안 2. key-value 로 구성된 vector 값을 NetworkFilter에 추가해서 UI에서 조건을 준 항목 만큼 조건을 주는 방식

## 예상되는 문제점
- 현재 운영중인 실 사이트에서 raw log 검색시 NewworkFilter에 조건을 source, time 값 이외에 ip 또는 port를 추가 조건으로 주었을때, 저장된 데이터 양이 많으면 검색 시간이 오래 걸립니다.
- 추가 조건을 주었을때 검색 시간이 더 오래 걸릴 거라고 예상 됩니다.

## 추가적인 고려사항
-  REview rocksdb에 저장된 탐지로그를 대상으로 하는 판정 기능중에 패킷 속성값을 조건으로 주는 기능이 있는데, 이 역시 위와 유사한 추가 조건을 EventListFilterInput에 추가 해야 합니다.

**Comment by kimhanbeom** [comment]
해당 요구사항에 대해 구현하지 않도록 합의가 되어 close하였습니다.
