### ISSUE TITLE
GraphQL API `logRawEvents`에 커서 기능 추가

### ISSUE THREAD

**Issue by msk** [aicers/giganto#42]
선행 이슈: #50 

`logRawEvents`에 다음과 같이 커서 관련 인자를 추가하고 [커서 커넥션](https://relay.dev/graphql/connections.htm)을 구현합니다.

```graphql
logRawEvents(source: !String, kind: !String, after: String, before: String, first: Int, last: Int): [String!]!
```

**Comment by BLYKIM** [comment]
현재 query가 오면
1. source값으로 db에서 key를 보고 value를 가져옴
2. deserialize
3. value의 kind를 보고 데이터를 보내주고있는데 

커서 커넥션을 구현하는 과정에서 3번 이후의 데이터를 가지고 처리를 하는지
db에서 kind까지 가지고 데이터를 처리하는 log_events 함수를 추가해야할지 궁금합니다

**Comment by msk** [comment]
말씀하신 두 방법이 기능상, 성능상 차이가 있나요? 구현 설계상 더 바람직한 쪽을 고르려는 거면 저는 후자처럼 db의 내부 저장 방식이 드러나지 않는 걸 선호합니다.

**Comment by BLYKIM** [comment]
생각해보니 두가지 방법은 결국 구현 위치만 달라진거네요.
궁금한점을 예를 들면 first 10개만 보고싶다는 query가 왔을 때 db에서 데이터를 뽑고 kind가 같은 리스트를 골라내서 거기서 10개를 보내주게되는데
그 과정을 반복적으로 수행한다면 비효율적이지 않은가하는 생각이 들어서 더 적절한 방법이 있을까 궁금했습니다.
