### ISSUE TITLE
오래된 레코드 삭제 속도 향상

### ISSUE THREAD

**Issue by msk** [aicers/giganto#45]
선행 이슈: #40

`storage::retain_periodically`에서는 오래된 레코드(raw event)를 삭제할 때 모든 키값을 읽은 후 시간을 하나씩 비교하는 방법을 쓰고 있습니다. 이 방법은 저장된 레코드 수가 많은 경우 매우 큰 메모리를 필요로 하고, 삭제하는데에 시간도 오래 걸립니다. #40 에서 만든 source 목록을 이용하면 각 source별로 스토리지 내에서 삭제해야 하는 시각의 위치를 바로 찾아갈 수 있으므로 필요한 메모리와 시간을 대폭 줄일 수 있습니다.

**Comment by kimhanbeom** [comment]
@msk 
conn, dns,http,rdp같은 경우는 key의 형태가 source/timestamp로 동일하여 같은 코드로 동일한 범위 삭제 동작이 가능합니다.
그러나 log의 경우는 key의 형태가 source/kind/timestamp라서 동일한 코드로 처리가 불가능하고 기존의 timestamp 위치를 통한 비교 동작으로 처리해야 될 것으로 보입니다. 두가지 처리 동작을 구분하여 코드를 작성하면 될까요?

**Comment by msk** [comment]
예, 지금은 그게 최선일 듯 합니다. log의 경우는 추후 성능 저하가 심하면 kind도 source처럼 목록을 따로 관리하는 걸 고려해야 할 수 있겠네요.
