### ISSUE TITLE
로그 저장 Key 변경

### ISSUE THREAD

**Issue by BLYKIM** [aicers/giganto#50]
Key를 "source 0u8 kind timestamp in big-endian"의 형태로 저장합니다

관련 이슈: #25, #42

**Comment by msk** [comment]
제가 처음에 저런 형태로 key를 제안하긴 했는데, 어차피 timestamp의 바이트 수가 정해져 있으므로 @kimhanbeom 이 구현한 것처럼 timestamp 앞에는 구분자(0u8)를 빼는 것이 낫겠습니다.

**Comment by BLYKIM** [comment]
이슈 수정했습니다.
