### ISSUE TITLE
Sysmon 이벤트에 대한 GraphQL Query 결과에 source, agent_name, agent_id 추가

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#501]
GraphQL query를 이용해서 Sysmon 이벤트를 조회할 때 그 결과에 다음 필드들을 추가해주세요.
* source
* agent_name
* agent_id

**Comment by BLYKIM** [comment]
GraphQL 이벤트 조회 시 source값은 필수항목인데 필드에 따로 추가해야하는 이유가 있나요?

**Comment by syncpark** [comment]
@BLYKIM 다른 프로토콜 이벤트들을 보니 source는 없네요. `source`는 제외하는게 좋겠습니다.
