### ISSUE TITLE
Statistics 데이터의 Key에 코어 아이디를 추가할 때 String 형태로 변환해서 저장하도록 수정

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#503]
## 요약
Statistics DB의 core id를 Key에 추가할 때 String으로 변환한 후에 추가하도록 수정

## 상세
Statistics DB의 Key는
* source(String.as_byes()) + core id(u32.to_be_bytes()) + timestamp(i64.to_be_bytes())

core id가 u32를 byte로 변환해서 Key에 추가되므로 다른 DB의 키가 모두 String(as_bytes())로 사용되는 것과 충돌이 있습니다.
예를 들면 Statistics DB의 키의 경우만 Key를 생성하거나 혹은 필터링할 때 별도 처리가 필요하게 됩니다.

그래서 core id를 String으로 변환한 후에 Key에 추가한다면 다른 DB의 키와 같은 방식으로 처리할 수 있게됩니다.

**Comment by kimhanbeom** [comment]
해당 내용의 수정은 https://github.com/aicers/giganto/commit/7392fb6277c4c509b96e42fb1085bf6ba31cb149 에서 적용되었으나 migration 부분도 추가되야 합니다.
