### ISSUE TITLE
giganto 시스템을 연결하는 주요 heap 변수의 type 정의 위치 수정 & 명칭 수정

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/giganto#596]
1. main, publish, ingest, peer 등 giganto 통신 전반에 걸쳐 공유되는 주요 heap 변수들의 type 정의 위치를 수정할 필요가 있습니다.
- AS-IS : src/ingest.rs에 type 정의
- TO-BE : src/main.rs에 type 정의 &&  Arc::new(RwLock::new(HashMap::new()) 를 PacketSources::new() 로 변경하여 가독성 획득

2. 현재의 type 명칭을 더 정확히 합니다.
- AS-IS -> TO-BE
- PacketSources -> PcapSources, 혹은 더 나은 명칭
- Sources -> IngestSources, 혹은 더 나은 명칭

cf. 관련 코드 부분입니다.
```rust
// src/main.rs
    loop {
        let packet_sources = Arc::new(RwLock::new(HashMap<String, Connection>::new()));
        let sources = Arc::new(RwLock::new(HashMap::new()));
        let stream_direct_channel = Arc::new(RwLock::new(HashMap::new()));


// src/ingest.rs
pub type PacketSources = Arc<RwLock<HashMap<String, Connection>>>;
pub type Sources = Arc<RwLock<HashMap<String, DateTime<Utc>>>>;
pub type StreamDirectChannel = Arc<RwLock<HashMap<String, UnboundedSender<Vec<u8>>>>>;
```

**Comment by sehkone** [comment]
@syncpark , 의견 좀 주세요.
