### ISSUE TITLE
Maybe improve rocksDB fetch performance with `batched_multi_get_cf`

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/giganto#597]
## Proposal
AS-IS `get_cf` 를 TO-BE `batched_multi_get_cf` 로 변경하면, 성능 향상 가능성이 있어 보입니다.
timestamps 배열이 클수록 성능 향상이 가시적일 것으로 보이며, timestamps 배열이 작다면 그렇지 않을 것으로 추측됩니다.

### AS-IS
https://github.com/aicers/giganto/blob/234bd5513bb55b756c28ab055e3175909725b825/src/storage.rs#L575-L594

### TO-BE
```rust
    pub fn batched_multi_get_from_ts<'ts>(
        &self,
        cf: &ColumnFamily,
        source: &str,
        timestamps: &'ts [DateTime<Utc>],
    ) -> Vec<(&'ts DateTime<Utc>, Vec<u8>)> {
        let keys = timestamps.iter().map(|timestamp| {
            StorageKey::builder()
                .start_key(source)
                .end_key(timestamp.timestamp_nanos_opt().unwrap_or(i64::MAX))
                .build()
                .key()
        });

        let result_vector: Vec<(&DateTime<Utc>, Vec<u8>)> = timestamps
            .iter()
            .zip(self.db.batched_multi_get_cf(cf, keys, false))
            .filter_map(|(timestamp, result_value)| {
                result_value
                    .ok()
                    .map(|val| (timestamp, val.unwrap().deref().to_vec()))
            })
            .collect();

        result_vector
    }
```
추가 확인이 필요한 사항
- ~~batched_multi_get_cf 의 전제조건이 만족되었는지 체크 필요 : SST file 들이 default block based table format 이어야 함.~~
  - -> 확인완료. BlockBasedTable 포맷 사용 중. 
- batched_multi_get_cf의 3번째 인자를 true로 하면서 keys을 rust에서 직접 sort할 때의 성능이 더 좋은지 확인 필요
- timestamps 배열의 길이가 어느정도인지, 실제 서비스 운영 관점에서 파악
  - NOTE: timestamps 배열의 길이는 이벤트마다 다를 수 있으므로, `get_cf` 와 `batched_multi_get_cf` 를 둘 다 구현해놓고, 적절히 선택적으로 사용하는 방향이 좋아보임.
- multi_get_from_ts와 유사한 multi_get_from_source 도 유사한 변경이 가능한지 확인 필요
- 변경 전후 성능 테스트

## 관련 rocksdb 문서
https://github.com/facebook/rocksdb/blob/e7896f03ad8fc50962909483fc0069d6ecead50d/include/rocksdb/c.h#L541-L571

**Comment by syncpark** [comment]
수정 찬성입니다. Giganto는 아직까지는 성능향상 방법이 별로 없어서 이런 수정사항은 환영입니다.
