### ISSUE TITLE
Release 0.17.0

### ISSUE THREAD

**Issue by sehkone** [aicers/giganto#657]
Due to modifications in GraphQL APIs originating from the Giganto cluster update, it's necessary to launch a new version. This will enable users to adjust their code in response to these changes.

**Comment by sophie-cluml** [comment]
## Release Checklist
- [ ] Make a PR
  - [ ] update version in `Cargo.toml`
  - [ ] update `CHANGELOG.md`
  - [ ] run `cargo update`
- [ ] Release with tag
- [ ] Share the release
