### ISSUE TITLE
Request for New Release Without Redis Dependency

### ISSUE THREAD

**Issue by msk** [aicers/giganto#677]
We, Petabi developers, have been running Giganto to test our proprietary system. However, we encountered a challenge with the introduction of the Redis dependency in version 0.17.0. This requirement has significantly complicated our development and testing processes. Setting up an additional server, especially without extensive documentation on configuration, has presented hurdles for our team.

We noticed, with much relief and gratitude, that a recent commit (2f4496b08b4b2b1649960854cd3ff7fd301d68d8) has removed the Redis dependency, addressing the very challenge we've been facing. Given the impact of this change, we kindly request the consideration of a new release that incorporates this update. A new release without the Redis requirement would greatly benefit us.

cc: @atyoshioka

**Comment by sophie-cluml** [comment]
## Release Checklist
- [ ] Make a PR
  - [ ] update version in `Cargo.toml`
  - [ ] update `CHANGELOG.md`
  - [ ] run `cargo update`
- [ ] Release with tag
- [ ] Share the release
