### ISSUE TITLE
Netflow5/Netflow9/Seculog DB migration 

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/giganto#692]
0.19.0 release 하기 전에  https://github.com/aicers/giganto/pull/687 작업에서 변경사항이 migration 될 수 있도록 하는 작업이 필요합니다. https://github.com/aicers/giganto/pull/687 에서 아래와 같은 변경이 있었습니다.

기존 db의 key=> pr 이후 db의 key
- netflow5:  "netflow5" + timestamp => source + timestamp 
- netflow9 : "netflow9" + timestamp => source + timestamp
- seculog : kind + timestamp => source + kind(보안로그타입) + timestamp

**Comment by sophie-cluml** [comment]
@kimhanbeom 위와 같은 작업이 0.19.0 에 포함되어야할 것 같은데 확인 부탁드립니다.

**Comment by kimhanbeom** [comment]
@sophie-cluml 
현재 netflow5/netflow9/seculog의 db key는 바뀌었지만 아직까지 해당 프로토콜에 대한 데이터를 저장하고 있지 않았어서 migration이 필요하지 않을 것 같습니다.

**Comment by sophie-cluml** [comment]
네 PR에 migration 코드가 없는 것으로 미루어 볼 때, 고객사에서 해당 프로토콜 데이터를 아직까지 저장하지 않았을 것이라고 추측하고 있었습니다. 지금 당장 고객사에서 경험하고 있는 bug를 빠르게 수정하기 위해서 꼭 필요한 작업에 migration이 불필요한 것으로 이해되었거든요.

다만 migration 코드의 작성 여부는 고객사의 db에 이미 데이터가 존재하는가가 기준이 아니라, giganto의 과거 버전들이 forward compatiblity 를 가지도록 하는 데에 초점을 두고 고려해야 한다고 보고 있습니다. 이 지점에 있어서 forward compatibilty를 보장하는 것이 불가능하거나 정말 불필요한 경우를 제외하고는 이를 보장하도록 해야한다고 생각되어요. 

이번에 migration을 작성하지 않으면 migration 관점에서 COMPATIBLE_VERSION_REQ 이 다음과 같이 변하게 됩니다.
```rust
const COMPATIBLE_VERSION_REQ: &str = ">0.13.0-alpha,<=0.18.0";   // as-is
const COMPATIBLE_VERSION_REQ: &str = ">=0.19.0,<0.20.0";  // to-be
```

이것은 0.19.0 에서 forward compatibility 가 깨진다는 것을 의미합니다. 이렇게 되면 0.19.0 미만 버전을 쓰고 있던 사람은 0.19.0 이상의 버전으로 자연스럽게 버전 업그레이드를 할 수가 없습니다.

**Comment by sophie-cluml** [comment]
이 이슈의 작업자는 꼭 David이 아니라 누구든(저 포함) 괜찮다고 보고 있기 때문에 위에 description에 적은 내용이 맞는 방향인지 여부 관점에서 확인 부탁드립니다.

**Comment by kimhanbeom** [comment]
데이터와 상관없이 forward compatibilty을 보장하는 쪽으로 작업하는게 맞는 것 같습니다. 다만 기존에도 migration 작성은 release pr에 포함해서 진행했으므로 release와 함꼐 제가 진행하겠습니다.

**Comment by sophie-cluml** [comment]
네 매우 감사합니다. 그런데 release PR 은 별도로 하는 것으로 하고 있어서 migration 별도 / release 별도로 진행하는 것으로 부탁드립니다.
