### ISSUE TITLE
Giganto loses connection with Piglet during database cleanup operation

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#702]
### Description
During the DB clean up task that is run once a day in Giganto, all connections from Piglet are lost, and the connection is reconnected only after the clean up task is completed.

#### Todo
- [ ] Convert `retain_periodically()` function to individual thread instead of `async thread`

Discussion: https://github.com/aicers/giganto/discussions/671

**Comment by sophie-cluml** [comment]
안녕하세요. 이 이슈는 (rocksdb진영의 용어 상) Write Stall 을 막기 위한 시도로 이해하고 있습니다.
정보의 축적 및 이슈 파악을 위해 retention이 돌아가는 시점을 포함하고 있는 rocksdb `LOG` 파일이 있다면 공유해주실 수 있을까요? (giganto 어플리케이션 log가 아닌 rocksdb log)

**Comment by sophie-cluml** [comment]
공유 감사합니다.
