### ISSUE TITLE
Update dependencies for mitigating vulnerability

### ISSUE THREAD

**Issue by sehkone** [aicers/giganto#726]
Refer to https://github.com/aicers/giganto/security/dependabot/22

Even `cargo update` might not fail in resolving the above, depending on the dependencies of the crates. If this is the case, please notify us about which crate causes it, and we will discuss it later.

**Comment by kimhanbeom** [comment]
The current dependency for `h2` is
- `warp 0.3.6`/`mockito 1.4.0` -> `hyper 0.14.28` -> `h2 0.3.25`

I checked the repositories for each crate and found that `mockito` has an updated version of `hyper`, but no release for that version yet. and `warp`, there is an issue and pr for `hyper`, but it doesn't seem to be progressing.

**Comment by sehkone** [comment]
> The current dependency for `h2` is
> 
> * `warp 0.3.6`/`mockito 1.4.0` -> `hyper 0.14.28` -> `h2 0.3.25`
> 
> I checked the repositories for each crate and found that `mockito` has an updated version of `hyper`, but no release for that version yet. and `warp`, there is an issue and pr for `hyper`, but it doesn't seem to be progressing.

mockito의 경우 hyper 새 버전 사용이 main 브랜치에는 업데이트가 되었는데 그걸 아직 릴리스하기 전이라는 말인가요?

**Comment by sehkone** [comment]
Could you visit the GitHub pages for Warp and Mockito and set up monitoring to alert you about any status changes?

**Comment by sehkone** [comment]
@kimhanbeom 
This should belong to the "pending" category in our to-do list project, which is the number 10 of our policy.

**Comment by kimhanbeom** [comment]
Since `H2` doesn't require a new release to version up (`0.3.26`), I'll continue with the current issue.
