### ISSUE TITLE
Piglet 혹은 REproduce로부터 이벤트를 배치로 받아서 처리

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#737]
이벤트를 수신하는 Async task의 호출 횟수를 줄이면서 한 번의 호출에 더 많은 이벤트를 처리하여 성능을 높이기 위한 수정입니다.

Tis branch에 패치가 완료되었고 실망 시험에서도 별 문제없이 이전 보다 성능이 높아졌습니다.
Main branch에도 이 패치를 추가할 필요가 있습니다.

이 패치는 REproduce, Piglet과 동시에 릴리즈되도록 수정해야 합니다.
이 패치를 적용하기 전에 Giganto-client 0.17.0~~과 Commit 627cd8e~~이 먼저 적용되어야 합니다. (#730)

Related: #708

**Comment by sehkone** [comment]
@syncpark @sophie-cluml 여기에도 규칙 21번 위반이 있네요.
