### ISSUE TITLE
너무 많은 이벤트로 인해 Rocks DB 깨지는 문제

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#754]
Tis branch의 Giganto 버전은 현재 평균 200,000건 이상의 이벤트를 1초에 수신하고 (최대 270,000건), 저장합니다.
1일로 환산하면 약 200억건의 이벤트를 처리하는데 그중에서 95% 정도가 `Conn`(세션) 이벤트입니다. 
이제 Main branch도 수정되었으니 같은 상황이 예상됩니다.

하루에 약 190억건의 이벤트가 `Conn` DB에 저장되는데, 이를 감당하기 쉽지 않아서 Compaction 작업이나 Heavy event search 작업중에 Rocks DB가 깨지는 문제가 종종 발생하고 있습니다.

아래와 같은 방법으로 해결해보려고 합니다.

DB 깨지는 문제 해결
- [ ] `Conn` 이벤트를 하루 10억건 이하로 저장할 수 있도록 다수의 DB로 분산 저장한다.
- [ ] 분산된 DB 구조에서 이벤트를 검색할 수 있도록 검색기능을 수정한다.
- [ ] `Conn` 이벤트만이 아니라 다른 이벤트도 관리자가 지정할 경우 DB를 분산하도록 기능을 확장한다.
- [ ] Compaction 작업의 동작방식 수정
    - Giganto에 저장되는 이벤트가 많지 않다면, 현재 방식 그대로 Compaction 작업을 매일 지정된 시간에 주기적으로 실행한다.
    - Giganto에 저장되는 이벤트가 많을 경우 매일 주기적으로 하는 방식은 사용하지 않는다. 대신 1주일마다 DB를 점검하는 시간을 갖고, 이때 Giganto를 재시작하면서 Compaction을 한번만(1주일에) 하는 방식으로 동작한다.

의견 부탁드립니다.

**Comment by sehkone** [comment]
@syncpark 논의가 좀 길어질 수도 있으니 이를 dicussiond으로 옮기는 것이 어떨까요?

**Comment by syncpark** [comment]
Giganto는 public repository이니 patio에 올리겠습니다.
그리고 지금 Giganto discussion에 있는 성능 관련 discussion도 patio로 옮겼으면 합니다.

**Comment by syncpark** [comment]
이번 이슈는 좀 더 논의가 필요해서 discussion으로 이동했으니 여기서 Close하겠습니다.

**Comment by sehkone** [comment]
@syncpark dicussion으로 이동하는 것은 오른쪽 "Convert to discussion" 기능을 사용하면 되는데, 알고 계신가요?

**Comment by sehkone** [comment]
@syncpark @sophie-cluml, 이슈 등을 public repo에서 private repo로 이동시키고 싶을 때에는 close하고 다시 open하기 보다는 이동이 더 좋겠습니다. close한 것이 public에서 확인이 가능하니까요.
