### ISSUE TITLE
export file name 수정

### ISSUE THREAD

**Issue by MW-Kim** [aicers/giganto#757]
## 배경
* 현재 raw log 에 대해서 export 할때 file명 규칙은 protocol + timestamp 입니다.
* log  db 에는 기타 모든 비정형 로그를 저장 할 수 있습니다.
* 이 log db에 저장되어 있는 raw log를 export 하면 file명이 (log or seculog) + timestamp 형식이라서 해당 파일명만 보고 구분이 되지 않습니다.
* log db 를 export 할때는 해당 로그를 구분 할 수 있도록 kind 값이 추가 되어야 합니다.
## Tasks

- [x] main
- [x] tis

**Comment by kimhanbeom** [comment]
해당 이슈 완료되어 close 합니다.
