### ISSUE TITLE
Support giganto-client 0.19.0

### ISSUE THREAD

**Issue by syncpark** [aicers/giganto#768]
BOOTP, DHCP가 추가되었습니다.
이를 지원하기위해 giganto-client 0.18.0을 적용해야 합니다.

**Comment by syncpark** [comment]
pending: aicers/giganto-client#121

**Comment by kimhanbeom** [comment]
https://github.com/aicers/giganto-client/pull/125 가 포함된 release 0.19.0를 적용해야하므로 현재 이슈의 타이틀을 0.19.0으로 변경하겠습니다.
