### ISSUE TITLE
Change command-line interface : local configuration 과 cert 정보를 커맨드라인으로 전달

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/giganto#779]
### Background
Giganto will soon support fetching full configuration from central management server. Giganto will still be able to run using configurations provided from local configuration file. This change calls for the change of the command line interface for running Giganto.

### Details

One possible command line interface implementation is below:
```
module_executable [-c path_to_config] [--cert path_to_cert] [--key path_to_key] [--ca path_to_ca] 
```

 For normal operation where the module fetches configuration from central management server, it can be run as 
```
 module_executable --cert cert_file --key key_file --ca root_file
```

If it needs to read the configuration locally, it can be run as
```
 module_executable -c local_config --cert cert_file --key key_file --ca root_file
```

- Path to cert files need to support both absolute and relative paths.
- This issue involves removing fields in `Settings`, which are going to be provided as cmd args.
- We need to update README.md and CHANGELOG.md
- We might need to utilize command line argument parsing library, such as `clap`

**Comment by sophie-cluml** [comment]
@BLYKIM 기존에 이슈에 적힌 것은 범용적인 예시라서 giganto에 좀 더 정확히 맞도록 central server address를 제거하였습니다. 참고부탁드립니다.

**Comment by BLYKIM** [comment]
안그래도 쓰임새가 궁금해 오시면 얘기해보려했는데 알겠습니다! `--ca` 부분도 이전에 정해진 규칙에 따라 `--root` 로 변경하였습니다.

**Comment by sehkone** [comment]
@BLYKIM @sophie-cluml 
Could you tell me which rule specified `--root`?

**Comment by BLYKIM** [comment]
@sehkone 규칙이라는 말이 어색했을지 모르겠습니다. 이전의 discussion에서 config값의 이름들을 unifying 했었던 건으로 root를 썼었습니다. https://github.com/orgs/aicers/discussions/20#discussioncomment-8991084

**Comment by sehkone** [comment]
> @sehkone 규칙이라는 말이 어색했을지 모르겠습니다. 이전의 discussion에서 config값의 이름들을 unifying 했었던 건으로 root를 썼었습니다. https://github.com/orgs/aicers/discussions/20#discussioncomment-8991084

Got it. But this is public, so the link is not allowed.

**Comment by BLYKIM** [comment]
링크부분 수정하였습니다.

**Comment by sehkone** [comment]
@BLYKIM @sophie-cluml 
`--root` is ambiguous. It should be either `--root-ca` or `--ca`. As you know, since "ca" includes "root ca", either option should be specified properly according to the context.

**Comment by sehkone** [comment]
> @BLYKIM @sophie-cluml `--root` is ambiguous. It should be either `--root-ca` or `--ca`. As you know, since "ca" includes "root ca", either option should be specified properly according to the context.

I just want to mention that `--root-ca` and `--ca` are not our options any more, according to the discussion.
