### ISSUE TITLE
Modify to use ring as the rustls cryptography option

### ISSUE THREAD

**Issue by kimhanbeom** [aicers/giganto#812]
currently, giganto is using aws-lc-rs as the cryptograph, but we want to change to ring for the following reasons.

  1. Compatibility: aws-lc-rs has compatibility issues with Ubuntu 20.04. While we could use a feature flag to conditionally compile with ring on Ubuntu 20.04, this adds unnecessary complexity to our build process. ring, on the other hand, builds successfully on both Ubuntu 20.04 and 22.x without any special accommodations.
  
  2. Performance: the performance advantage of aws-lc-rs over ring is minimal, at most 2%. This marginal gain doesn't justify the added complexity and potential issues introduced by using aws-lc-rs.
  
  3. FIPS Compliance: While aws-lc-rs offers FIPS compliance, we currently don't have an immediate need for this feature. If FIPS compliance becomes a requirement in the future, we can revisit this decision.
  
  4. Safety: ring is written in 100% safe Rust, which aligns well with our focus on software safety and security.

**Comment by sophie-cluml** [comment]
I have a question regarding the background of this issue. According to the documents [here](https://aws.github.io/aws-lc-rs/faq.html#can-i-run-aws-lc-rs-on-x-platform-or-architecture) and [here](https://aws.github.io/aws-lc-rs/requirements/linux.html), it seems that aws-lc-rs is expected to work on our Ubuntu 20.04 and 22.04 environments (which I believe is x86_64-unknown-linux-gnu). Given this, I suspect there might be some bugs in the aws-lc-rs project. If there are known issues, could you please share them?

**Comment by syncpark** [comment]
@sophie-cluml 
"aws-lc-rs" library can be compiled in Ubuntu 20.04 only after gcc and glibc are upgraded from 9.4 to 11.4.
But gcc 9.4 is installed in the machine of customer site, the glibc runtime library must be upgraded before the program with aws-lc-rs is running.

**Comment by sophie-cluml** [comment]
아니면, 일단 이 이슈에 연결된 PR을 리뷰 & 머지하되, 언젠가 aws-lc-rs로 이행하는 별도의 issue를 생성해두면 잊지 않고 언젠가 추후 핸들링 하는 것도 가능한 방향으로 보여서 그렇게 하면 어떨까요? 의견 부탁드립니다.
