### ISSUE TITLE
giganto가 local configuration 으로 동작하고 있다는 것을  GraphQL client 가 알 수 있도록, get config 용 GraphQL API 를 업데이트

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/giganto#817]
giganto 는 local / remote configuration 두가지 방식으로 동작할 수 있습니다.

"get config" 관련 GraphQL API 에서 "local configuration 으로 동작하는 모드에 있다는 사실"이  유저에게 알려질 수 있도록 하여야 합니다.  여기서, "get config" 관련 GraphQL API는 이슈 작성 시점 기준, API 이름이 `getGigantoConfig` 입니다. 하지만 작업 시점에는 해당 API 이름이 변경되었을 수 있으므로 확인 후 작업이 필요합니다.

----

(English Translation)

Giganto can work in two ways: local / remote configuration.

The “get config” related GraphQL API need to allow the user to be informed that they are “in a mode that operates with local configuration”.  Here, the GraphQL API for “get config” is named `getGigantoConfig` at the time of creating the issue. However, the name of the API may have changed by the time we start working on this, so we need to check before starting on this task.

**Comment by BLYKIM** [comment]
giganto는 현재 manager server와 독립적으로 remote configuration 방식이 존재하지 않는데, 자세한 설명이 필요할 것 같습니다.
`getGigantoConfig`는 `gigantoConfig`에서 `config`로 변경된 GraphQL Query를 생각하면 될까요?

**Comment by sophie-cluml** [comment]
> getGigantoConfig는 gigantoConfig에서 config로 변경된 GraphQL Query를 생각하면 될까요?

**Comment by sophie-cluml** [comment]
좀 더 부연하겠습니다.

graphql/status.rs 에 다음의 API 함수가 있습니다. 이 함수는 현재 Result<settings::Config> 를 리턴하고 있습니다.
```
async fn config<'ctx>(&self, ctx: &Context<'ctx>) -> Result<settings::Config>
```

이 이슈가 resolve 되기 위하여서는 `Result<ConfigInfo>` 와 같은 것이 리턴되면 될 것 같습니다.

```
pub struct ConfigInfo {  // 더 적절한 네이밍을 고민해주시면 좋을것 같습니다.
   local: bool,  // local configuration으로 동작 중이라면 true 
   config: settings::Config,
};
```
