### ISSUE TITLE
Proposal: Change `setGigantoConfig` to return `Result<bool>` instead of `Result<String>`

### ISSUE THREAD

**Issue by sophie-cluml** [aicers/giganto#820]
Currently, the `setGigantoConfig` API returns `Ok("Done")` upon success. However, this string doesn't provide additional value beyond indicating that the request succeeded. To simplify the API and make it more straightforward, I propose changing the return ~~`Ok(())`~~ `Ok(true)` or `Ok(false)` when the operation is successful. This will result in a cleaner and more concise API interface.

**Comment by henry0715-dev** [comment]
@sophie-cluml 
It seems that async-graphql cannot handle the return of an empty tuple `()`. I would like to hear your thoughts on converting it to `Result<bool>`.

**Comment by sophie-cluml** [comment]
네 제가 착각했습니다. bool이 좋을 것 같네요. 감사합니다.
