### ISSUE TITLE
Add Code Coverage in Giganto

### ISSUE THREAD

**Issue by soojlee0106** [aicers/giganto#91]
Refer to similar commit in Github Server to add code coverage feature.

**Comment by soojlee0106** [comment]
Branch를 따로 생성해서 PR을 올렸더니 check가 fail하는 현상이 일어납니다. soo91 branch에 해당 코드를 작성하였습니다. 검토 부탁드립니다.

**Comment by msk** [comment]
문제는 giganto의 tests 폴더에 있는 테스트가 giganto를 별도로 돌고 있는 걸 전제로 하고 있어서 tarpaulin이 테스트를 실행하면 gignato가 없으므로 타임아웃이 난다는 점입니다. 해결책은

1. 우리가 CI에서 `--bin giganto` 옵션을 줘서 unit tests만 실행하고 tests 폴더에 있는 테스트는 실행하지 않는 것처럼 tarpaulin도 tests 폴더의 테스트는 제외하도록 하는 것(구체적인 방법은 찾지 못했습니다),
2. tests 폴더에 있는 테스트들을 전부 unit test 형식으로 바꿔서 따로 giganto를 실행하지 않아도 되도록 하는 것

입니다. 2번은 [oinq](https://github.com/petabi/oinq)의 unit test가 쓰는 방식을 참조하면 가능하긴 할텐데, `async` task들을 실행하는 순서를 잘 맞춰주지 않으면 deadlock이 생길 수 있어서 간단하진 않습니다.

**Comment by soojlee0106** [comment]
> 문제는 giganto의 tests 폴더에 있는 테스트가 giganto를 별도로 돌고 있는 걸 전제로 하고 있어서 tarpaulin이 테스트를 실행하면 gignato가 없으므로 타임아웃이 난다는 점입니다. 해결책은
> 
> 1. 우리가 CI에서 `--bin giganto` 옵션을 줘서 unit tests만 실행하고 tests 폴더에 있는 테스트는 실행하지 않는 것처럼 tarpaulin도 tests 폴더의 테스트는 제외하도록 하는 것(구체적인 방법은 찾지 못했습니다),
> 2. tests 폴더에 있는 테스트들을 전부 unit test 형식으로 바꿔서 따로 giganto를 실행하지 않아도 되도록 하는 것
> 
> 입니다. 2번은 [oinq](https://github.com/petabi/oinq)의 unit test가 쓰는 방식을 참조하면 가능하긴 할텐데, `async` task들을 실행하는 순서를 잘 맞춰주지 않으면 deadlock이 생길 수 있어서 간단하진 않습니다.

[Cargo Tarpaulin 대한 blog](https://morioh.com/p/bfe6c22e43bf)를 참고하여 test folder에 있는 특정 test를 무시하도록 수정했습니다.
